export const TITLE_SUCCESS = 'Sucesso'
export const TITLE_ERROR = 'Oooops!'
export const TEXT_DEFAULT_SUCCESS = 'Operação realizada com sucesso.'
export const TEXT_USER_CREATING = 'Usuário cadastrado com sucesso.'
export const TEXT_DEFAULT_ERROR = 'Ocorreu um erro inesperado! '
export const TEXT_ERROR_LOGIN = 'E-mail e/ou senha inválido.'
export const TEXT_LOG_IN = 'Faça o login.'
export const TEXT_PASSWORD_RESET = 'Solicitação de redefinição de senha enviada, verifique sua caixa de entrada do e-mail.'